import { NameCode } from "../model";

export const allBookGenres: NameCode[] = [
    {name: 'Aventura', codename: 'Aventura'},
    {name: 'Acción', codename: 'Acción'},
    {name: 'Autoayuda', codename: 'Autoayuda'},
    {name: 'Biografías', codename: 'Biografías'},
    {name: 'Ciencia Ficción', codename: 'Ciencia Ficción'},
    {name: 'Educativos', codename: 'Educativos'},
    {name: 'Fantasia', codename: 'Fantasia'},
    {name: 'Infantiles', codename: 'Infantiles'},
    {name: 'Novelas románticas', codename: 'Novelas románticas'},
    {name: 'Poesías', codename: 'Poesías'},
    {name: 'Policiales', codename: 'Policiales'},
    {name: 'Terror', codename: 'Terror'},
];

export const allCountries: NameCode[] = [
    {name: "Afganistán", codename: "AF"},
    {name: "Albania", codename: "AL"},
    {name: "Alemania", codename: "DE"},
    {name: "Andorra", codename: "AD"},
    {name: "Angola", codename: "AO"},
    {name: "Anguila", codename: "AI"},
    {name: "Antártida", codename: "AQ"},
    {name: "Antigua y Barbuda", codename: "AG"},
    {name: "Arabia Saudita", codename: "SA"},
    {name: "Argelia", codename: "DZ"},
    {name: "Argentina", codename: "AR"},
    {name: "Armenia", codename: "AM"},
    {name: "Aruba", codename: "AW"},
    {name: "Australia", codename: "AU"},
    {name: "Austria", codename: "AT"},
    {name: "Azerbaiyán", codename: "AZ"},
    {name: "Bélgica", codename: "BE"},
    {name: "Bahamas", codename: "BS"},
    {name: "Bahrein", codename: "BH"},
    {name: "Bangladesh", codename: "BD"},
    {name: "Barbados", codename: "BB"},
    {name: "Belice", codename: "BZ"},
    {name: "Benín", codename: "BJ"},
    {name: "Bhután", codename: "BT"},
    {name: "Bielorrusia", codename: "BY"},
    {name: "Birmania", codename: "MM"},
    {name: "Bolivia", codename: "BO"},
    {name: "Bosnia y Herzegovina", codename: "BA"},
    {name: "Botsuana", codename: "BW"},
    {name: "Brasil", codename: "BR"},
    {name: "Brunéi", codename: "BN"},
    {name: "Bulgaria", codename: "BG"},
    {name: "Burkina Faso", codename: "BF"},
    {name: "Burundi", codename: "BI"},
    {name: "Cabo Verde", codename: "CV"},
    {name: "Camboya", codename: "KH"},
    {name: "Camerún", codename: "CM"},
    {name: "Canadá", codename: "CA"},
    {name: "Chad", codename: "TD"},
    {name: "Chile", codename: "CL"},
    {name: "China", codename: "CN"},
    {name: "Chipre", codename: "CY"},
    {name: "Ciudad del Vaticano", codename: "VA"},
    {name: "Colombia", codename: "CO"},
    {name: "Comoras", codename: "KM"},
    {name: "República del Congo", codename: "CG"},
    {name: "República Democrática del Congo", codename: "CD"},
    {name: "Corea del Norte", codename: "KP"},
    {name: "Corea del Sur", codename: "KR"},
    {name: "Costa de Marfil", codename: "CI"},
    {name: "Costa Rica", codename: "CR"},
    {name: "Croacia", codename: "HR"},
    {name: "Cuba", codename: "CU"},
    {name: "Curazao", codename: "CW"},
    {name: "Dinamarca", codename: "DK"},
    {name: "Dominica", codename: "DM"},
    {name: "Ecuador", codename: "EC"},
    {name: "Egipto", codename: "EG"},
    {name: "El Salvador", codename: "SV"},
    {name: "Emiratos Árabes Unidos", codename: "AE"},
    {name: "Eritrea", codename: "ER"},
    {name: "Eslovaquia", codename: "SK"},
    {name: "Eslovenia", codename: "SI"},
    {name: "España", codename: "ES"},
    {name: "Estados Unidos de América", codename: "US"},
    {name: "Estonia", codename: "EE"},
    {name: "Etiopía", codename: "ET"},
    {name: "Filipinas", codename: "PH"},
    {name: "Finlandia", codename: "FI"},
    {name: "Fiyi", codename: "FJ"},
    {name: "Francia", codename: "FR"},
    {name: "Gabón", codename: "GA"},
    {name: "Gambia", codename: "GM"},
    {name: "Georgia", codename: "GE"},
    {name: "Ghana", codename: "GH"},
    {name: "Gibraltar", codename: "GI"},
    {name: "Granada", codename: "GD"},
    {name: "Grecia", codename: "GR"},
    {name: "Groenlandia", codename: "GL"},
    {name: "Guadalupe", codename: "GP"},
    {name: "Guam", codename: "GU"},
    {name: "Guatemala", codename: "GT"},
    {name: "Guayana Francesa", codename: "GF"},
    {name: "Guernsey", codename: "GG"},
    {name: "Guinea", codename: "GN"},
    {name: "Guinea Ecuatorial", codename: "GQ"},
    {name: "Guinea-Bissau", codename: "GW"},
    {name: "Guyana", codename: "GY"},
    {name: "Haití", codename: "HT"},
    {name: "Honduras", codename: "HN"},
    {name: "Hong kong", codename: "HK"},
    {name: "Hungría", codename: "HU"},
    {name: "India", codename: "IN"},
    {name: "Indonesia", codename: "ID"},
    {name: "Irán", codename: "IR"},
    {name: "Irak", codename: "IQ"},
    {name: "Irlanda", codename: "IE"},
    {name: "Isla Bouvet", codename: "BV"},
    {name: "Isla de Man", codename: "IM"},
    {name: "Isla de Navidad", codename: "CX"},
    {name: "Isla Norfolk", codename: "NF"},
    {name: "Islandia", codename: "IS"},
    {name: "Islas Bermudas", codename: "BM"},
    {name: "Islas Caimán", codename: "KY"},
    {name: "Islas Cocos (Keeling)", codename: "CC"},
    {name: "Islas Cook", codename: "CK"},
    {name: "Islas de Åland", codename: "AX"},
    {name: "Islas Feroe", codename: "FO"},
    {name: "Islas Georgias del Sur y Sandwich del Sur", codename: "GS"},
    {name: "Islas Heard y McDonald", codename: "HM"},
    {name: "Islas Maldivas", codename: "MV"},
    {name: "Islas Malvinas", codename: "FK"},
    {name: "Islas Marianas del Norte", codename: "MP"},
    {name: "Islas Marshall", codename: "MH"},
    {name: "Islas Pitcairn", codename: "PN"},
    {name: "Islas Salomón", codename: "SB"},
    {name: "Islas Turcas y Caicos", codename: "TC"},
    {name: "Islas Ultramarinas Menores de Estados Unidos", codename: "UM"},
    {name: "Islas Vírgenes Británicas", codename: "VG"},
    {name: "Islas Vírgenes de los Estados Unidos", codename: "VI"},
    {name: "Israel", codename: "IL"},
    {name: "Italia", codename: "IT"},
    {name: "Jamaica", codename: "JM"},
    {name: "Japón", codename: "JP"},
    {name: "Jersey", codename: "JE"},
    {name: "Jordania", codename: "JO"},
    {name: "Kazajistán", codename: "KZ"},
    {name: "Kenia", codename: "KE"},
    {name: "Kirguistán", codename: "KG"},
    {name: "Kiribati", codename: "KI"},
    {name: "Kuwait", codename: "KW"},
    {name: "Líbano", codename: "LB"},
    {name: "Laos", codename: "LA"},
    {name: "Lesoto", codename: "LS"},
    {name: "Letonia", codename: "LV"},
    {name: "Liberia", codename: "LR"},
    {name: "Libia", codename: "LY"},
    {name: "Liechtenstein", codename: "LI"},
    {name: "Lituania", codename: "LT"},
    {name: "Luxemburgo", codename: "LU"},
    {name: "México", codename: "MX"},
    {name: "Mónaco", codename: "MC"},
    {name: "Macao", codename: "MO"},
    {name: "Macedônia", codename: "MK"},
    {name: "Madagascar", codename: "MG"},
    {name: "Malasia", codename: "MY"},
    {name: "Malawi", codename: "MW"},
    {name: "Mali", codename: "ML"},
    {name: "Malta", codename: "MT"},
    {name: "Marruecos", codename: "MA"},
    {name: "Martinica", codename: "MQ"},
    {name: "Mauricio", codename: "MU"},
    {name: "Mauritania", codename: "MR"},
    {name: "Mayotte", codename: "YT"},
    {name: "Micronesia", codename: "FM"},
    {name: "Moldavia", codename: "MD"},
    {name: "Mongolia", codename: "MN"},
    {name: "Montenegro", codename: "ME"},
    {name: "Montserrat", codename: "MS"},
    {name: "Mozambique", codename: "MZ"},
    {name: "Namibia", codename: "NA"},
    {name: "Nauru", codename: "NR"},
    {name: "Nepal", codename: "NP"},
    {name: "Nicaragua", codename: "NI"},
    {name: "Niger", codename: "NE"},
    {name: "Nigeria", codename: "NG"},
    {name: "Niue", codename: "NU"},
    {name: "Noruega", codename: "NO"},
    {name: "Nueva Caledonia", codename: "NC"},
    {name: "Nueva Zelanda", codename: "NZ"},
    {name: "Omán", codename: "OM"},
    {name: "Países Bajos", codename: "NL"},
    {name: "Pakistán", codename: "PK"},
    {name: "Palau", codename: "PW"},
    {name: "Palestina", codename: "PS"},
    {name: "Panamá", codename: "PA"},
    {name: "Papúa Nueva Guinea", codename: "PG"},
    {name: "Paraguay", codename: "PY"},
    {name: "Perú", codename: "PE"},
    {name: "Polinesia Francesa", codename: "PF"},
    {name: "Polonia", codename: "PL"},
    {name: "Portugal", codename: "PT"},
    {name: "Puerto Rico", codename: "PR"},
    {name: "Qatar", codename: "QA"},
    {name: "Reino Unido", codename: "GB"},
    {name: "República Centroafricana", codename: "CF"},
    {name: "República Checa", codename: "CZ"},
    {name: "República Dominicana", codename: "DO"},
    {name: "República de Sudán del Sur", codename: "SS"},
    {name: "Reunión", codename: "RE"},
    {name: "Ruanda", codename: "RW"},
    {name: "Rumanía", codename: "RO"},
    {name: "Rusia", codename: "RU"},
    {name: "Sahara Occidental", codename: "EH"},
    {name: "Samoa", codename: "WS"},
    {name: "Samoa Americana", codename: "AS"},
    {name: "San Bartolomé", codename: "BL"},
    {name: "San Cristóbal y Nieves", codename: "KN"},
    {name: "San Marino", codename: "SM"},
    {name: "San Martín (Francia)", codename: "MF"},
    {name: "San Pedro y Miquelón", codename: "PM"},
    {name: "San Vicente y las Granadinas", codename: "VC"},
    {name: "Santa Elena", codename: "SH"},
    {name: "Santa Lucía", codename: "LC"},
    {name: "Santo Tomé y Príncipe", codename: "ST"},
    {name: "Senegal", codename: "SN"},
    {name: "Serbia", codename: "RS"},
    {name: "Seychelles", codename: "SC"},
    {name: "Sierra Leona", codename: "SL"},
    {name: "Singapur", codename: "SG"},
    {name: "Sint Maarten", codename: "SX"},
    {name: "Siria", codename: "SY"},
    {name: "Somalia", codename: "SO"},
    {name: "Sri lanka", codename: "LK"},
    {name: "Sudáfrica", codename: "ZA"},
    {name: "Sudán", codename: "SD"},
    {name: "Suecia", codename: "SE"},
    {name: "Suiza", codename: "CH"},
    {name: "Surinám", codename: "SR"},
    {name: "Svalbard y Jan Mayen", codename: "SJ"},
    {name: "Swazilandia", codename: "SZ"},
    {name: "Tayikistán", codename: "TJ"},
    {name: "Tailandia", codename: "TH"},
    {name: "Taiwán", codename: "TW"},
    {name: "Tanzania", codename: "TZ"},
    {name: "Territorio Británico del Océano Índico", codename: "IO"},
    {name: "Territorios Australes y Antárticas Franceses", codename: "TF"},
    {name: "Timor Oriental", codename: "TL"},
    {name: "Togo", codename: "TG"},
    {name: "Tokelau", codename: "TK"},
    {name: "Tonga", codename: "TO"},
    {name: "Trinidad y Tobago", codename: "TT"},
    {name: "Tunez", codename: "TN"},
    {name: "Turkmenistán", codename: "TM"},
    {name: "Turquía", codename: "TR"},
    {name: "Tuvalu", codename: "TV"},
    {name: "Ucrania", codename: "UA"},
    {name: "Uganda", codename: "UG"},
    {name: "Uruguay", codename: "UY"},
    {name: "Uzbekistán", codename: "UZ"},
    {name: "Vanuatu", codename: "VU"},
    {name: "Venezuela", codename: "VE"},
    {name: "Vietnam", codename: "VN"},
    {name: "Wallis y Futuna", codename: "WF"},
    {name: "Yemen", codename: "YE"},
    {name: "Yibuti", codename: "DJ"},
    {name: "Zambia", codename: "ZM"},
    {name: "Zimbabue", codename: "ZW"},
]